= I18n Country Subdivisions

:version: 0.5

image:https://github.com/mihxil/i18n-subdivisions/actions/workflows/maven.yml/badge.svg?[Build Status,link=https://github.com/mihxil/i18n-subdivisions/actions/workflows/maven.yml]
image:https://codecov.io/gh/mihxil/i18n-subdivisions/branch/main/graph/badge.svg[codecov,link=https://codecov.io/gh/mihxil/i18n-subdivisions]
image:https://img.shields.io/maven-central/v/org.meeuw.i18n/i18n-subdivision-enums.svg?label=Maven%20Central[Maven Central,link=https://central.sonatype.com/artifact/org.meeuw.i18n/i18n-subdivision-enums]
image:https://www.javadoc.io/badge/org.meeuw.i18n/i18n-subdivision-enums.svg?color=blue[javadoc,link=https://www.javadoc.io/doc/org.meeuw.i18n/i18n-subdivision-enums]

== Overview


Package to support internationalization, specifically the Subdivision (provinces/states/region)
defined in ISO 3166-2.

It depends on the link:https://github.com/mihxil/i18n-regions#countries[i18n-regions-countries] package for defining all the Countries used.

This is forked from https://github.com/tobias-/i18n-subdivisions which doesn't seem to be maintained. I changed the coordinates and package and I am maintaining it myself now.

The author is well aware that there are bound to be problems in the data set. If nothing else, the data changes over time, so please submit issues when something is wrong (preferably with a verifiably link to the correct data).

While the information on what kind of subdivision it is (region, island, state, province, city etc), they are too many different kinds for them to be readily usable and thus they are not available.

== License

Apache License, Version 2.0

== Download

[source,sh]
----
git clone https://github.com/mihxil/i18n-subdivisions.git

----

All code is generated by the groovy script `src/build/groovy/generateSubdivisions.groovy` from the html files in `src/build/resources/`.

== Building

A new set of html files is dowloaded by issueing

[source,sh]
----
mvn clean install -Pdownload
----
They are stored in src/build/resources and committed to versioning. These files are converted to java enums then. These appear as generated sources and are not committed.


The resulting list is however converted to .txt in a test-case and compared to a copy in src/test/resources. This way it is easily detected wether there were changes.

== Releasing

[source,sh]
----
mvn release:prepare release:perform -Pdownload-subdivisions
----

== Examples

List all the subdivision codes available for a specific country.

[source,java]
----
include::src/test/java/org/meeuw/i18n/subdivision/SubdivisionsTest.java[tag=belgium,indent=0]
----

This is wrapped also in https://github.com/mihxil/i18n-regions#subdivisions-of-countries[i18n-regions], which would make every enum defined in this project available as a more generic 'Region' object, and also be accessible via the RegionService.
[source,java]
----
include::src/test/java/org/meeuw/i18n/subdivision/SubdivisionsTest.java[tag=utrechtRegionService,indent=0]
----

Another example
[source,java]
----
include::src/test/java/org/meeuw/i18n/subdivision/SubdivisionsTest.java[tag=greatbritain,indent=0]
----

== Maven

[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>org.meeuw.i18n</groupId>
    <artifactId>i18n-subdivision-enums</artifactId>
    <version>{version}</version>
</dependency>
----

== Gradle

[source,gradle,subs="attributes+"]
----
dependencies {
    compile 'org.meeuw.i18n:i18n-subdivision-enums:{version}'
}
----

== See Also

* https://en.wikipedia.org/wiki/ISO_3166-2[ISO 3166-2 on Wikipedia]
* http://www.unece.org/cefact/locode/subdivisions.html[Source of the codes] (seems to be broken)

== TODO

* Verify with another source of the codes
* If anyone wants them, include subdivision types in the enum
* drop dependency on neovisionaries, which is unmaintained

== HISTORY


|===
| version | changes/remarks | date

|0.5 | dropped nvi18n.version dependency, renamed interface to 'CountrySubdivision'. Being a 'RegionProvider' | september 2025

|0.4 | adopted to org.meeuw |

|===
