= I18n Country Subdivisions
:version: 0.5
:toc:
:toclevels: 1


image:https://github.com/mihxil/i18n-subdivisions/actions/workflows/maven.yml/badge.svg?[Build Status,link=https://github.com/mihxil/i18n-subdivisions/actions/workflows/maven.yml]
image:https://codecov.io/gh/mihxil/i18n-subdivisions/graph/badge.svg?token=JhUiuqyvHO[codecov,link=https://codecov.io/gh/mihxil/i18n-subdivisions]
image:https://img.shields.io/maven-central/v/org.meeuw.i18n/i18n-subdivision-enums.svg?label=Maven%20Central[Maven Central,link=https://central.sonatype.com/artifact/org.meeuw.i18n/i18n-subdivision-enums]
image:https://www.javadoc.io/badge/org.meeuw.i18n/i18n-subdivision-enums.svg?color=blue[javadoc,link=https://www.javadoc.io/doc/org.meeuw.i18n/i18n-subdivision-enums]

== Overview


Package to support internationalization, specifically the Subdivision (provinces/states/region)
defined in ISO 3166-2.

It depends on the link:https://github.com/mihxil/i18n-regions#countries[i18n-regions-countries] package for defining all the Countries used.

This is forked from https://github.com/tobias-/i18n-subdivisions which doesn't seem to be maintained. I changed the coordinates and package and I am maintaining it myself now.

The author is well aware that there are bound to be problems in the data set. If nothing else, the data changes over time, so please submit issues when something is wrong (preferably with a verifiably link to the correct data).

While the information on what kind of subdivision it is (region, island, state, province, city etc), they are too many different kinds for them to be readily usable and thus they are not available.


== Examples

List all the subdivision codes available for a specific country.

[source,java]
----
include::src/test/java/org/meeuw/i18n/subdivision/SubdivisionsTest.java[tag=belgium,indent=0]
----

This is wrapped also in https://github.com/mihxil/i18n-regions#subdivisions-of-countries[i18n-regions], which would make every enum defined in this project available as a more generic 'Region' object, and also be accessible via the RegionService.
[source,java]
----
include::src/test/java/org/meeuw/i18n/subdivision/SubdivisionsTest.java[tag=utrecht,indent=0]
----

Another example
[source,java]
----
include::src/test/java/org/meeuw/i18n/subdivision/SubdivisionsTest.java[tag=greatbritain,indent=0]
----


== See Also

* https://github.com/mihxil/i18n-regions
* https://en.wikipedia.org/wiki/ISO_3166-2[ISO 3166-2 on Wikipedia]
* http://www.unece.org/cefact/locode/subdivisions.html[Source of the codes] (seems to be broken)



== Building

All code is generated by the groovy script `link:src/build/groovy/generateSubdivisions.groovy[generateSubdivisions.groovy]` from the html files in `link:src/build/resources/[src/build/resources]`.

A new set of html files is downloaded by issuing

[source,sh]
----
mvn clean install -Pdownload
----
They are stored in src/build/resources and committed to versioning. These files are converted to java enums then. These appear as generated sources and are not committed.

The resulting list is however converted to .txt in a test-case and compared to a copy in src/test/resources. This way it is easily detected whether there were changes.



== History

=== TODO

* Verify with another source of the codes
* If anyone wants them, include subdivision types in the enum



|===
| version | changes/remarks | date

|0.6 | also dropped region provider stuff again. This will be done in i18n-regions-subdivisions This is now just a clean set of dependency-less enums. | oktober 2025

|0.5 | dropped  direct nvi18n dependency, renamed interface to 'CountrySubdivision'. Being a 'RegionProvider' | september 2025

|0.4 | adopted to org.meeuw |

|===
