---
# This workflow will build a Java project with Maven
name: build

on:
  push:
    branches: [main, "[0-9]+.[0-9]+-SNAPSHOT"]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    steps:

      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
      - name: Build and deploy with Maven
        run: |
          mvn -B -Pdeploy test deploy
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - uses: codecov/codecov-action@v4
        with:
          files: ./target/site/jacoco/jacoco.xml
          verbose: true
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Tests results
          files: "**/target/surefire-reports/*.xml"

