---
# This workflow will build a Java project with Maven
name: build

on:
  push:
    branches: [main, "[0-9]+.[0-9]+-SNAPSHOT"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - name: Cancel previous Action
        uses: styfle/cancel-workflow-action@0.9.1
        continue-on-error: true  # for act
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "ossrh", "username": "mihxil", "password": "${{secrets.OSSRH_PASSWORD}}"}]'
      - uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET_KEY }}
          passphrase: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - name: Build and deploy with Maven
        run: |
          which pinentry
          mvn -B test deploy
      - uses: codecov/codecov-action@v3
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        if: always()

