---
# This workflow will build a Java project with Maven
name: build

on:
  push:
    branches: [main, "[0-9]+.[0-9]+-SNAPSHOT"]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    strategy:
      matrix:
        include:
          - java: 21
            target: 'test'
          - java: 25-ea
            target: 'test'
          - java: 17
            target: 'test'
          - java: 11
            target: 'deploy'
    runs-on: ubuntu-latest
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
      - name: Build and deploy with Maven
        run: |
          mvn -B -Pdeploy ${{ matrix.target }}
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - uses: codecov/codecov-action@v5
        with:
          files: ./target/site/jacoco/jacoco.xml
          verbose: true
        if: matrix.target == 'deploy'
      - name: Publish Unit Test Results ${{ matrix.java }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Tests results
          files: "target/surefire-reports/*.xml"

