---
name: release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
          server-id: ossrh
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: GPG_SECRET_KEY_PASSPHRASE
      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: 'github $GITHUB_ACTOR'
          email: 'michiel.meeuwissen@gmail.com'
          token: '${{ secrets.GITHUB_TOKEN  }}'
      - name: Release
        run: |
          mvn --batch-mode  -Darguments=-DskipTests  -DpushChanges=false release:prepare
          git push --atomic -v --follow-tags
          mvn --batch-mode -Darguments=-DskipTests release:perform
        env:
          SONATYPE_USERNAME: mihxil
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}

