---
name: release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "ossrh", "username": "mihxil", "password": "${{secrets.OSSRH_PASSWORD}}"}]'
      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          passphrase: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: 'github $GITHUB_ACTOR'
          email: 'michiel.meeuwissen@gmail.com'
          token: '${{ secrets.GITHUB_TOKEN  }}'
      - name: Release
        run: |
          mvn --batch-mode  -Darguments=-DskipTests  -DpushChanges=false release:prepare
          git push --atomic -v --follow-tags
          mvn --batch-mode -Darguments=-DskipTests release:perform

