---
name: release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: 'github $GITHUB_ACTOR'
          email: 'michiel.meeuwissen@gmail.com'
          token: '${{ secrets.GITHUB_TOKEN  }}'
      - name: Release
        run: |
          mvn --batch-mode  -Darguments=-DskipTests  -DpushChanges=false release:prepare
          git push --atomic -v --follow-tags
          mvn --batch-mode -Pdeploy -Darguments=-DskipTests release:perform
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}

